"""Type stubs for feagi_data_processing module."""

from typing import Any

# Genome module
class genome:
    """Genomic structures module containing cortical types and dimensions."""
    
    class PyCorticalID: ...
    class PyCorticalType: ...
    class PyCorticalTypeVariant: ...
    class PyCorticalSensorType: ...
    class PyCoreCorticalType: ...
    class PyCorticalGroupingIndex: ...
    class PyCorticalIOChannelIndex: ...
    class PySingleChannelDimensions: ...

# IO Data module
class io_data:
    """IO data types and variants module."""
    
    class PyIOTypeVariant: ...

# IO Processing module
class io_processing:
    """IO processing utilities module."""
    
    class bytes:
        """Byte structure handling module."""
        class PyFeagiByteStructure: ...
    
    class processors:
        """Data processing modules."""
        class PyLinearAverageRollingWindowProcessor: ...
        class PyIdentityFloatProcessor: ...
        class PyIdentityImageFrameProcessor: ...
        class PyLinearScaleTo0And1: ...
        class PyLinearScaleToM1And1: ...
    
    class cache:
        """Caching mechanisms for sensors."""
        class PySensorCache: ...

# Neuron Data module
class neuron_data:
    """Neuron data structures and utilities module."""
    
    class xyzp:
        """XYZP neuron data handling module."""
        class PyCorticalMappedXYZPNeuronData: ...
        class PyNeuronXYZPArrays: ...
        class PyNeuronXYZP: ...