use std::sync::MutexGuard;
use feagi_connector_core::ConnectorAgent;
use crate::feagi_connector_core::data_types::descriptors::PyMiscDataDimensions;
use pyo3::{pyclass, pymethods, PyResult};
use pyo3::prelude::*;
use feagi_connector_core::data_pipeline::{PipelineStageProperties, PipelineStagePropertyIndex};
use feagi_connector_core::data_types::*;
use feagi_connector_core::data_types::descriptors::{ImageFrameProperties, MiscDataDimensions};
use feagi_connector_core::motor_device_cache::MotorDeviceCache;
use feagi_connector_core::sensor_device_cache::SensorDeviceCache;
use feagi_connector_core::wrapped_io_data::WrappedIOData;
use crate::{create_pyclass_no_clone, __base_py_class_shared};
use crate::py_error::PyFeagiError;
use crate::feagi_connector_core::data_types::descriptors::*;
use crate::feagi_connector_core::data_pipeline::pipeline_stage_properties::{PyPipelineStageProperties};
use crate::feagi_connector_core::wrapped_io_data::py_object_to_wrapped_io_data;
use crate::feagi_data_serialization::PyFeagiByteContainer;

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// DEVELOPER NOTE: THIS FILE HAS A LARGE REGION WHICH HAS AUTOGENERATED CODE BY BUILDRS WHICH MAY OVERWRITE YOUR CHANGES.
// TO TURN ON, THE BELOW COMMENT LINE MUST READ *EXACTLY* "BUILDRS_ON" (NO SPACES), CHANGE TO ANY OTHER VALUE TO DISABLE.
// FURTHER NOTE: WHEN OFF, SOME ERROR CHECKING OF THE IDE MAY BE NON=FUNCTIONAL!
//BUILDRS_OFF



create_pyclass_no_clone!(PyConnectorAgent, ConnectorAgent, "ConnectorAgent");

/*
impl PyConnectorAgent {
    fn get_sensor_cache(&self) -> MutexGuard<SensorDeviceCache> {
        self.inner.get_sensor_cache()
    }

    fn get_motor_cache(&self) -> MutexGuard<MotorDeviceCache> {
        self.inner.get_motor_cache()
    }
}

 */



//region Motor Functions
//BUILDRS_MOTOR_DEVICE_START


//BUILDRS_MOTOR_DEVICE_END
//endregion

//region Sensor Functions
//BUILDRS_SENSOR_DEVICE_START

//BUILDRS_SENSOR_DEVICE_END
//endregion