use crate::feagi_connector_core::data::descriptors::PyMiscDataDimensions;
use pyo3::{pyclass, pymethods, PyResult};
use pyo3::prelude::*;
use feagi_connector_core::IOCache;
use feagi_data_structures::genomic::descriptors::{CorticalChannelCount, CorticalChannelIndex, CorticalGroupIndex, NeuronDepth};
use feagi_data_structures::motor_definition;
use feagi_connector_core::data_pipeline::PipelineStagePropertyIndex;
use feagi_connector_core::data_types::*;
use feagi_connector_core::data_types::descriptors::MiscDataDimensions;
use crate::py_error::PyFeagiError;
use crate::feagi_connector_core::data::descriptors::*;
use crate::feagi_connector_core::data::*;
use crate::feagi_connector_core::data_pipeline::pipeline_stage_properties::{extract_pipeline_stage_properties_from_py, PyPipelineStageProperties};
use crate::feagi_connector_core::wrapped_io_data::py_object_to_wrapped_io_data;
use crate::feagi_data_serialization::PyFeagiByteContainer;
use crate::feagi_data_structures::genomic::descriptors::{PyCorticalChannelCount, PyNeuronDepth, PyCorticalChannelIndex, PyCorticalGroupIndex, PyPipelineStagePropertyIndex};

////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// DEVELOPER NOTE: THIS FILE HAS A LARGE REGION WHICH HAS AUTOGENERATED CODE BY BUILDRS WHICH MAY OVERWRITE YOUR CHANGES.
// TO TURN ON, THE BELOW COMMENT LINE MUST READ *EXACTLY* "BUILDRS_ON" (NO SPACES), CHANGE TO ANY OTHER VALUE TO DISABLE
//BUILDRS_ON

#[pyclass]
#[pyo3(name = "IOCache")]
#[derive()]
pub struct PyIOCache {
    inner: IOCache
}

#[pymethods]
impl PyIOCache {

    #[new]
    pub fn new() -> Self {
        PyIOCache {
            inner: IOCache::new()
        }
    }

    //region AUTOGENERATED CODE

    //region Motor Functions
    //BUILDRS_MOTOR_DEVICE_START
    //region rotary_motor_absolute_linear

    pub fn motor_register_rotary_motor_absolute_linear(
        &mut self,
        py: Python<'_>,
        group: PyObject,
        number_of_channels: PyObject,
        z_neuron_depth: PyObject
    ) -> PyResult<()>
    {
        let group: CorticalGroupIndex = PyCorticalGroupIndex::try_get_from_py_object(py, group).map_err(PyFeagiError::from)?;
        let number_of_channels: CorticalChannelCount = PyCorticalChannelCount::try_get_from_py_object(py, number_of_channels).map_err(PyFeagiError::from)?;
        let z_neuron_depth: NeuronDepth = PyNeuronDepth::try_get_from_py_object(py, z_neuron_depth).map_err(PyFeagiError::from)?;

        self.inner.motor_register_rotary_motor_absolute_linear(group, number_of_channels, z_neuron_depth).map_err(PyFeagiError::from)?;
        Ok(())
    }

    pub fn motor_try_read_preprocessed_cached_value_rotary_motor_absolute_linear(
        &mut self,
        py: Python<'_>,
        group: PyObject,
        channel: PyObject,
    ) -> PyResult<PySignedPercentage>
    {
        let group: CorticalGroupIndex = PyCorticalGroupIndex::try_get_from_py_object(py, group).map_err(PyFeagiError::from)?;
        let channel: CorticalChannelIndex = PyCorticalChannelIndex::try_get_from_py_object(py, channel).map_err(PyFeagiError::from)?;

        let unwrapped: SignedPercentage = self.inner.motor_try_read_preprocessed_cached_value_rotary_motor_absolute_linear(group, channel).map_err(PyFeagiError::from)?;
        Ok(unwrapped.into())
    }

    pub fn motor_try_read_postprocessed_cached_value_rotary_motor_absolute_linear(
        &mut self,
        py: Python<'_>,
        group: PyObject,
        channel: PyObject,
    ) -> PyResult<PySignedPercentage>
    {
        let group: CorticalGroupIndex = PyCorticalGroupIndex::try_get_from_py_object(py, group).map_err(PyFeagiError::from)?;
        let channel: CorticalChannelIndex = PyCorticalChannelIndex::try_get_from_py_object(py, channel).map_err(PyFeagiError::from)?;

        let unwrapped: SignedPercentage = self.inner.motor_try_read_postprocessed_cached_value_rotary_motor_absolute_linear(group, channel).map_err(PyFeagiError::from)?;
        Ok(unwrapped.into())
    }

    //endregion

    //region rotary_motor_absolute_fractional

    pub fn motor_register_rotary_motor_absolute_fractional(
        &mut self,
        py: Python<'_>,
        group: PyObject,
        number_of_channels: PyObject,
        z_neuron_depth: PyObject
    ) -> PyResult<()>
    {
        let group: CorticalGroupIndex = PyCorticalGroupIndex::try_get_from_py_object(py, group).map_err(PyFeagiError::from)?;
        let number_of_channels: CorticalChannelCount = PyCorticalChannelCount::try_get_from_py_object(py, number_of_channels).map_err(PyFeagiError::from)?;
        let z_neuron_depth: NeuronDepth = PyNeuronDepth::try_get_from_py_object(py, z_neuron_depth).map_err(PyFeagiError::from)?;

        self.inner.motor_register_rotary_motor_absolute_fractional(group, number_of_channels, z_neuron_depth).map_err(PyFeagiError::from)?;
        Ok(())
    }

    pub fn motor_try_read_preprocessed_cached_value_rotary_motor_absolute_fractional(
        &mut self,
        py: Python<'_>,
        group: PyObject,
        channel: PyObject,
    ) -> PyResult<PySignedPercentage>
    {
        let group: CorticalGroupIndex = PyCorticalGroupIndex::try_get_from_py_object(py, group).map_err(PyFeagiError::from)?;
        let channel: CorticalChannelIndex = PyCorticalChannelIndex::try_get_from_py_object(py, channel).map_err(PyFeagiError::from)?;

        let unwrapped: SignedPercentage = self.inner.motor_try_read_preprocessed_cached_value_rotary_motor_absolute_fractional(group, channel).map_err(PyFeagiError::from)?;
        Ok(unwrapped.into())
    }

    pub fn motor_try_read_postprocessed_cached_value_rotary_motor_absolute_fractional(
        &mut self,
        py: Python<'_>,
        group: PyObject,
        channel: PyObject,
    ) -> PyResult<PySignedPercentage>
    {
        let group: CorticalGroupIndex = PyCorticalGroupIndex::try_get_from_py_object(py, group).map_err(PyFeagiError::from)?;
        let channel: CorticalChannelIndex = PyCorticalChannelIndex::try_get_from_py_object(py, channel).map_err(PyFeagiError::from)?;

        let unwrapped: SignedPercentage = self.inner.motor_try_read_postprocessed_cached_value_rotary_motor_absolute_fractional(group, channel).map_err(PyFeagiError::from)?;
        Ok(unwrapped.into())
    }

    //endregion

    //region rotary_motor_incremental_linear

    pub fn motor_register_rotary_motor_incremental_linear(
        &mut self,
        py: Python<'_>,
        group: PyObject,
        number_of_channels: PyObject,
        z_neuron_depth: PyObject
    ) -> PyResult<()>
    {
        let group: CorticalGroupIndex = PyCorticalGroupIndex::try_get_from_py_object(py, group).map_err(PyFeagiError::from)?;
        let number_of_channels: CorticalChannelCount = PyCorticalChannelCount::try_get_from_py_object(py, number_of_channels).map_err(PyFeagiError::from)?;
        let z_neuron_depth: NeuronDepth = PyNeuronDepth::try_get_from_py_object(py, z_neuron_depth).map_err(PyFeagiError::from)?;

        self.inner.motor_register_rotary_motor_incremental_linear(group, number_of_channels, z_neuron_depth).map_err(PyFeagiError::from)?;
        Ok(())
    }

    pub fn motor_try_read_preprocessed_cached_value_rotary_motor_incremental_linear(
        &mut self,
        py: Python<'_>,
        group: PyObject,
        channel: PyObject,
    ) -> PyResult<PySignedPercentage>
    {
        let group: CorticalGroupIndex = PyCorticalGroupIndex::try_get_from_py_object(py, group).map_err(PyFeagiError::from)?;
        let channel: CorticalChannelIndex = PyCorticalChannelIndex::try_get_from_py_object(py, channel).map_err(PyFeagiError::from)?;

        let unwrapped: SignedPercentage = self.inner.motor_try_read_preprocessed_cached_value_rotary_motor_incremental_linear(group, channel).map_err(PyFeagiError::from)?;
        Ok(unwrapped.into())
    }

    pub fn motor_try_read_postprocessed_cached_value_rotary_motor_incremental_linear(
        &mut self,
        py: Python<'_>,
        group: PyObject,
        channel: PyObject,
    ) -> PyResult<PySignedPercentage>
    {
        let group: CorticalGroupIndex = PyCorticalGroupIndex::try_get_from_py_object(py, group).map_err(PyFeagiError::from)?;
        let channel: CorticalChannelIndex = PyCorticalChannelIndex::try_get_from_py_object(py, channel).map_err(PyFeagiError::from)?;

        let unwrapped: SignedPercentage = self.inner.motor_try_read_postprocessed_cached_value_rotary_motor_incremental_linear(group, channel).map_err(PyFeagiError::from)?;
        Ok(unwrapped.into())
    }

    //endregion

    //region rotary_motor_incremental_fractional

    pub fn motor_register_rotary_motor_incremental_fractional(
        &mut self,
        py: Python<'_>,
        group: PyObject,
        number_of_channels: PyObject,
        z_neuron_depth: PyObject
    ) -> PyResult<()>
    {
        let group: CorticalGroupIndex = PyCorticalGroupIndex::try_get_from_py_object(py, group).map_err(PyFeagiError::from)?;
        let number_of_channels: CorticalChannelCount = PyCorticalChannelCount::try_get_from_py_object(py, number_of_channels).map_err(PyFeagiError::from)?;
        let z_neuron_depth: NeuronDepth = PyNeuronDepth::try_get_from_py_object(py, z_neuron_depth).map_err(PyFeagiError::from)?;

        self.inner.motor_register_rotary_motor_incremental_fractional(group, number_of_channels, z_neuron_depth).map_err(PyFeagiError::from)?;
        Ok(())
    }

    pub fn motor_try_read_preprocessed_cached_value_rotary_motor_incremental_fractional(
        &mut self,
        py: Python<'_>,
        group: PyObject,
        channel: PyObject,
    ) -> PyResult<PySignedPercentage>
    {
        let group: CorticalGroupIndex = PyCorticalGroupIndex::try_get_from_py_object(py, group).map_err(PyFeagiError::from)?;
        let channel: CorticalChannelIndex = PyCorticalChannelIndex::try_get_from_py_object(py, channel).map_err(PyFeagiError::from)?;

        let unwrapped: SignedPercentage = self.inner.motor_try_read_preprocessed_cached_value_rotary_motor_incremental_fractional(group, channel).map_err(PyFeagiError::from)?;
        Ok(unwrapped.into())
    }

    pub fn motor_try_read_postprocessed_cached_value_rotary_motor_incremental_fractional(
        &mut self,
        py: Python<'_>,
        group: PyObject,
        channel: PyObject,
    ) -> PyResult<PySignedPercentage>
    {
        let group: CorticalGroupIndex = PyCorticalGroupIndex::try_get_from_py_object(py, group).map_err(PyFeagiError::from)?;
        let channel: CorticalChannelIndex = PyCorticalChannelIndex::try_get_from_py_object(py, channel).map_err(PyFeagiError::from)?;

        let unwrapped: SignedPercentage = self.inner.motor_try_read_postprocessed_cached_value_rotary_motor_incremental_fractional(group, channel).map_err(PyFeagiError::from)?;
        Ok(unwrapped.into())
    }

    //endregion

    //region positional_servo_absolute_linear

    pub fn motor_register_positional_servo_absolute_linear(
        &mut self,
        py: Python<'_>,
        group: PyObject,
        number_of_channels: PyObject,
        z_neuron_depth: PyObject
    ) -> PyResult<()>
    {
        let group: CorticalGroupIndex = PyCorticalGroupIndex::try_get_from_py_object(py, group).map_err(PyFeagiError::from)?;
        let number_of_channels: CorticalChannelCount = PyCorticalChannelCount::try_get_from_py_object(py, number_of_channels).map_err(PyFeagiError::from)?;
        let z_neuron_depth: NeuronDepth = PyNeuronDepth::try_get_from_py_object(py, z_neuron_depth).map_err(PyFeagiError::from)?;

        self.inner.motor_register_positional_servo_absolute_linear(group, number_of_channels, z_neuron_depth).map_err(PyFeagiError::from)?;
        Ok(())
    }

    pub fn motor_try_read_preprocessed_cached_value_positional_servo_absolute_linear(
        &mut self,
        py: Python<'_>,
        group: PyObject,
        channel: PyObject,
    ) -> PyResult<PySignedPercentage>
    {
        let group: CorticalGroupIndex = PyCorticalGroupIndex::try_get_from_py_object(py, group).map_err(PyFeagiError::from)?;
        let channel: CorticalChannelIndex = PyCorticalChannelIndex::try_get_from_py_object(py, channel).map_err(PyFeagiError::from)?;

        let unwrapped: SignedPercentage = self.inner.motor_try_read_preprocessed_cached_value_positional_servo_absolute_linear(group, channel).map_err(PyFeagiError::from)?;
        Ok(unwrapped.into())
    }

    pub fn motor_try_read_postprocessed_cached_value_positional_servo_absolute_linear(
        &mut self,
        py: Python<'_>,
        group: PyObject,
        channel: PyObject,
    ) -> PyResult<PySignedPercentage>
    {
        let group: CorticalGroupIndex = PyCorticalGroupIndex::try_get_from_py_object(py, group).map_err(PyFeagiError::from)?;
        let channel: CorticalChannelIndex = PyCorticalChannelIndex::try_get_from_py_object(py, channel).map_err(PyFeagiError::from)?;

        let unwrapped: SignedPercentage = self.inner.motor_try_read_postprocessed_cached_value_positional_servo_absolute_linear(group, channel).map_err(PyFeagiError::from)?;
        Ok(unwrapped.into())
    }

    //endregion

    //region positional_servo_absolute_fractional

    pub fn motor_register_positional_servo_absolute_fractional(
        &mut self,
        py: Python<'_>,
        group: PyObject,
        number_of_channels: PyObject,
        z_neuron_depth: PyObject
    ) -> PyResult<()>
    {
        let group: CorticalGroupIndex = PyCorticalGroupIndex::try_get_from_py_object(py, group).map_err(PyFeagiError::from)?;
        let number_of_channels: CorticalChannelCount = PyCorticalChannelCount::try_get_from_py_object(py, number_of_channels).map_err(PyFeagiError::from)?;
        let z_neuron_depth: NeuronDepth = PyNeuronDepth::try_get_from_py_object(py, z_neuron_depth).map_err(PyFeagiError::from)?;

        self.inner.motor_register_positional_servo_absolute_fractional(group, number_of_channels, z_neuron_depth).map_err(PyFeagiError::from)?;
        Ok(())
    }

    pub fn motor_try_read_preprocessed_cached_value_positional_servo_absolute_fractional(
        &mut self,
        py: Python<'_>,
        group: PyObject,
        channel: PyObject,
    ) -> PyResult<PySignedPercentage>
    {
        let group: CorticalGroupIndex = PyCorticalGroupIndex::try_get_from_py_object(py, group).map_err(PyFeagiError::from)?;
        let channel: CorticalChannelIndex = PyCorticalChannelIndex::try_get_from_py_object(py, channel).map_err(PyFeagiError::from)?;

        let unwrapped: SignedPercentage = self.inner.motor_try_read_preprocessed_cached_value_positional_servo_absolute_fractional(group, channel).map_err(PyFeagiError::from)?;
        Ok(unwrapped.into())
    }

    pub fn motor_try_read_postprocessed_cached_value_positional_servo_absolute_fractional(
        &mut self,
        py: Python<'_>,
        group: PyObject,
        channel: PyObject,
    ) -> PyResult<PySignedPercentage>
    {
        let group: CorticalGroupIndex = PyCorticalGroupIndex::try_get_from_py_object(py, group).map_err(PyFeagiError::from)?;
        let channel: CorticalChannelIndex = PyCorticalChannelIndex::try_get_from_py_object(py, channel).map_err(PyFeagiError::from)?;

        let unwrapped: SignedPercentage = self.inner.motor_try_read_postprocessed_cached_value_positional_servo_absolute_fractional(group, channel).map_err(PyFeagiError::from)?;
        Ok(unwrapped.into())
    }

    //endregion

    //region positional_servo_incremental_linear

    pub fn motor_register_positional_servo_incremental_linear(
        &mut self,
        py: Python<'_>,
        group: PyObject,
        number_of_channels: PyObject,
        z_neuron_depth: PyObject
    ) -> PyResult<()>
    {
        let group: CorticalGroupIndex = PyCorticalGroupIndex::try_get_from_py_object(py, group).map_err(PyFeagiError::from)?;
        let number_of_channels: CorticalChannelCount = PyCorticalChannelCount::try_get_from_py_object(py, number_of_channels).map_err(PyFeagiError::from)?;
        let z_neuron_depth: NeuronDepth = PyNeuronDepth::try_get_from_py_object(py, z_neuron_depth).map_err(PyFeagiError::from)?;

        self.inner.motor_register_positional_servo_incremental_linear(group, number_of_channels, z_neuron_depth).map_err(PyFeagiError::from)?;
        Ok(())
    }

    pub fn motor_try_read_preprocessed_cached_value_positional_servo_incremental_linear(
        &mut self,
        py: Python<'_>,
        group: PyObject,
        channel: PyObject,
    ) -> PyResult<PySignedPercentage>
    {
        let group: CorticalGroupIndex = PyCorticalGroupIndex::try_get_from_py_object(py, group).map_err(PyFeagiError::from)?;
        let channel: CorticalChannelIndex = PyCorticalChannelIndex::try_get_from_py_object(py, channel).map_err(PyFeagiError::from)?;

        let unwrapped: SignedPercentage = self.inner.motor_try_read_preprocessed_cached_value_positional_servo_incremental_linear(group, channel).map_err(PyFeagiError::from)?;
        Ok(unwrapped.into())
    }

    pub fn motor_try_read_postprocessed_cached_value_positional_servo_incremental_linear(
        &mut self,
        py: Python<'_>,
        group: PyObject,
        channel: PyObject,
    ) -> PyResult<PySignedPercentage>
    {
        let group: CorticalGroupIndex = PyCorticalGroupIndex::try_get_from_py_object(py, group).map_err(PyFeagiError::from)?;
        let channel: CorticalChannelIndex = PyCorticalChannelIndex::try_get_from_py_object(py, channel).map_err(PyFeagiError::from)?;

        let unwrapped: SignedPercentage = self.inner.motor_try_read_postprocessed_cached_value_positional_servo_incremental_linear(group, channel).map_err(PyFeagiError::from)?;
        Ok(unwrapped.into())
    }

    //endregion

    //region positional_servo_incremental_fractional

    pub fn motor_register_positional_servo_incremental_fractional(
        &mut self,
        py: Python<'_>,
        group: PyObject,
        number_of_channels: PyObject,
        z_neuron_depth: PyObject
    ) -> PyResult<()>
    {
        let group: CorticalGroupIndex = PyCorticalGroupIndex::try_get_from_py_object(py, group).map_err(PyFeagiError::from)?;
        let number_of_channels: CorticalChannelCount = PyCorticalChannelCount::try_get_from_py_object(py, number_of_channels).map_err(PyFeagiError::from)?;
        let z_neuron_depth: NeuronDepth = PyNeuronDepth::try_get_from_py_object(py, z_neuron_depth).map_err(PyFeagiError::from)?;

        self.inner.motor_register_positional_servo_incremental_fractional(group, number_of_channels, z_neuron_depth).map_err(PyFeagiError::from)?;
        Ok(())
    }

    pub fn motor_try_read_preprocessed_cached_value_positional_servo_incremental_fractional(
        &mut self,
        py: Python<'_>,
        group: PyObject,
        channel: PyObject,
    ) -> PyResult<PySignedPercentage>
    {
        let group: CorticalGroupIndex = PyCorticalGroupIndex::try_get_from_py_object(py, group).map_err(PyFeagiError::from)?;
        let channel: CorticalChannelIndex = PyCorticalChannelIndex::try_get_from_py_object(py, channel).map_err(PyFeagiError::from)?;

        let unwrapped: SignedPercentage = self.inner.motor_try_read_preprocessed_cached_value_positional_servo_incremental_fractional(group, channel).map_err(PyFeagiError::from)?;
        Ok(unwrapped.into())
    }

    pub fn motor_try_read_postprocessed_cached_value_positional_servo_incremental_fractional(
        &mut self,
        py: Python<'_>,
        group: PyObject,
        channel: PyObject,
    ) -> PyResult<PySignedPercentage>
    {
        let group: CorticalGroupIndex = PyCorticalGroupIndex::try_get_from_py_object(py, group).map_err(PyFeagiError::from)?;
        let channel: CorticalChannelIndex = PyCorticalChannelIndex::try_get_from_py_object(py, channel).map_err(PyFeagiError::from)?;

        let unwrapped: SignedPercentage = self.inner.motor_try_read_postprocessed_cached_value_positional_servo_incremental_fractional(group, channel).map_err(PyFeagiError::from)?;
        Ok(unwrapped.into())
    }

    //endregion

    //region gaze_absolute_linear

    pub fn motor_register_gaze_absolute_linear(
        &mut self,
        py: Python<'_>,
        group: PyObject,
        number_of_channels: PyObject,
        z_neuron_depth: PyObject
    ) -> PyResult<()>
    {
        let group: CorticalGroupIndex = PyCorticalGroupIndex::try_get_from_py_object(py, group).map_err(PyFeagiError::from)?;
        let number_of_channels: CorticalChannelCount = PyCorticalChannelCount::try_get_from_py_object(py, number_of_channels).map_err(PyFeagiError::from)?;
        let z_neuron_depth: NeuronDepth = PyNeuronDepth::try_get_from_py_object(py, z_neuron_depth).map_err(PyFeagiError::from)?;

        self.inner.motor_register_gaze_absolute_linear(group, number_of_channels, z_neuron_depth).map_err(PyFeagiError::from)?;
        Ok(())
    }

    pub fn motor_try_read_preprocessed_cached_value_gaze_absolute_linear(
        &mut self,
        py: Python<'_>,
        group: PyObject,
        channel: PyObject,
    ) -> PyResult<PyPercentage4D>
    {
        let group: CorticalGroupIndex = PyCorticalGroupIndex::try_get_from_py_object(py, group).map_err(PyFeagiError::from)?;
        let channel: CorticalChannelIndex = PyCorticalChannelIndex::try_get_from_py_object(py, channel).map_err(PyFeagiError::from)?;

        let unwrapped: Percentage4D = self.inner.motor_try_read_preprocessed_cached_value_gaze_absolute_linear(group, channel).map_err(PyFeagiError::from)?;
        Ok(unwrapped.into())
    }

    pub fn motor_try_read_postprocessed_cached_value_gaze_absolute_linear(
        &mut self,
        py: Python<'_>,
        group: PyObject,
        channel: PyObject,
    ) -> PyResult<PyPercentage4D>
    {
        let group: CorticalGroupIndex = PyCorticalGroupIndex::try_get_from_py_object(py, group).map_err(PyFeagiError::from)?;
        let channel: CorticalChannelIndex = PyCorticalChannelIndex::try_get_from_py_object(py, channel).map_err(PyFeagiError::from)?;

        let unwrapped: Percentage4D = self.inner.motor_try_read_postprocessed_cached_value_gaze_absolute_linear(group, channel).map_err(PyFeagiError::from)?;
        Ok(unwrapped.into())
    }

    //endregion

    //region gaze_incremental_linear

    pub fn motor_register_gaze_incremental_linear(
        &mut self,
        py: Python<'_>,
        group: PyObject,
        number_of_channels: PyObject,
        z_neuron_depth: PyObject
    ) -> PyResult<()>
    {
        let group: CorticalGroupIndex = PyCorticalGroupIndex::try_get_from_py_object(py, group).map_err(PyFeagiError::from)?;
        let number_of_channels: CorticalChannelCount = PyCorticalChannelCount::try_get_from_py_object(py, number_of_channels).map_err(PyFeagiError::from)?;
        let z_neuron_depth: NeuronDepth = PyNeuronDepth::try_get_from_py_object(py, z_neuron_depth).map_err(PyFeagiError::from)?;

        self.inner.motor_register_gaze_incremental_linear(group, number_of_channels, z_neuron_depth).map_err(PyFeagiError::from)?;
        Ok(())
    }

    pub fn motor_try_read_preprocessed_cached_value_gaze_incremental_linear(
        &mut self,
        py: Python<'_>,
        group: PyObject,
        channel: PyObject,
    ) -> PyResult<PyPercentage4D>
    {
        let group: CorticalGroupIndex = PyCorticalGroupIndex::try_get_from_py_object(py, group).map_err(PyFeagiError::from)?;
        let channel: CorticalChannelIndex = PyCorticalChannelIndex::try_get_from_py_object(py, channel).map_err(PyFeagiError::from)?;

        let unwrapped: Percentage4D = self.inner.motor_try_read_preprocessed_cached_value_gaze_incremental_linear(group, channel).map_err(PyFeagiError::from)?;
        Ok(unwrapped.into())
    }

    pub fn motor_try_read_postprocessed_cached_value_gaze_incremental_linear(
        &mut self,
        py: Python<'_>,
        group: PyObject,
        channel: PyObject,
    ) -> PyResult<PyPercentage4D>
    {
        let group: CorticalGroupIndex = PyCorticalGroupIndex::try_get_from_py_object(py, group).map_err(PyFeagiError::from)?;
        let channel: CorticalChannelIndex = PyCorticalChannelIndex::try_get_from_py_object(py, channel).map_err(PyFeagiError::from)?;

        let unwrapped: Percentage4D = self.inner.motor_try_read_postprocessed_cached_value_gaze_incremental_linear(group, channel).map_err(PyFeagiError::from)?;
        Ok(unwrapped.into())
    }

    //endregion

    //region miscellaneous_absolute

    pub fn motor_register_miscellaneous_absolute(
        &mut self,
        py: Python<'_>,
        group: PyObject,
        number_of_channels: PyObject,
        misc_dimensions: PyObject,
    ) -> PyResult<()>
    {
        let group: CorticalGroupIndex = PyCorticalGroupIndex::try_get_from_py_object(py, group).map_err(PyFeagiError::from)?;
        let number_of_channels: CorticalChannelCount = PyCorticalChannelCount::try_get_from_py_object(py, number_of_channels).map_err(PyFeagiError::from)?;
        let misc_dimensions: MiscDataDimensions = PyMiscDataDimensions::try_get_from_py_object(py, misc_dimensions).map_err(PyFeagiError::from)?;

        self.inner.motor_register_miscellaneous_absolute(group, number_of_channels, misc_dimensions).map_err(PyFeagiError::from)?;
        Ok(())
    }
    //endregion

    //region miscellaneous_incremental

    pub fn motor_register_miscellaneous_incremental(
        &mut self,
        py: Python<'_>,
        group: PyObject,
        number_of_channels: PyObject,
        misc_dimensions: PyObject,
    ) -> PyResult<()>
    {
        let group: CorticalGroupIndex = PyCorticalGroupIndex::try_get_from_py_object(py, group).map_err(PyFeagiError::from)?;
        let number_of_channels: CorticalChannelCount = PyCorticalChannelCount::try_get_from_py_object(py, number_of_channels).map_err(PyFeagiError::from)?;
        let misc_dimensions: MiscDataDimensions = PyMiscDataDimensions::try_get_from_py_object(py, misc_dimensions).map_err(PyFeagiError::from)?;

        self.inner.motor_register_miscellaneous_incremental(group, number_of_channels, misc_dimensions).map_err(PyFeagiError::from)?;
        Ok(())
    }
    //endregion

    //BUILDRS_MOTOR_DEVICE_END
    //endregion


    //endregion


    //region Sensors

    pub fn sensors_encode_cached_data_to_bytes(&mut self) -> PyResult<()> {
        self.inner.sensor_encode_data_to_bytes(0).map_err(PyFeagiError::from)?;
        Ok(())
    }

    pub fn sensor_get_byte_container(&mut self, py: Python<'_>) -> PyResult<PyFeagiByteContainer> {
        let byte_container = self.inner.sensor_copy_feagi_byte_container();
        Ok(byte_container.into())
    }

    //region Segmented Vision

    pub fn sensor_register_segmented_vision_absolute(&mut self, py: Python<'_>, group: PyObject,
                                                     number_of_channels: PyObject, input_image_properties: PyImageFrameProperties,
                                                     output_segment_properties: PySegmentedImageFrameProperties, gaze: PyGazeProperties) -> PyResult<()> {

        let cortical_group_index: CorticalGroupIndex = PyCorticalGroupIndex::try_get_from_py_object(py, group).map_err(PyFeagiError::from)?;
        let number_of_channels: CorticalChannelCount = PyCorticalChannelCount::try_get_from_py_object(py, number_of_channels).map_err(PyFeagiError::from)?;

        self.inner.sensor_register_segmented_vision_absolute(cortical_group_index,
                                                             number_of_channels, input_image_properties.into(),
                                                             output_segment_properties.into(), gaze.into()).map_err(PyFeagiError::from)?;
        Ok(())
    }

    pub fn sensor_write_segmented_vision_absolute(&mut self, py: Python<'_>, group: PyObject, channel: PyObject, data: PyObject) -> PyResult<()> {
        let cortical_group_index: CorticalGroupIndex = PyCorticalGroupIndex::try_get_from_py_object(py, group).map_err(PyFeagiError::from)?;
        let cortical_channel_index: CorticalChannelIndex = PyCorticalChannelIndex::try_get_from_py_object(py, channel).map_err(PyFeagiError::from)?;
        let wrapped_io_data = py_object_to_wrapped_io_data(py, data).map_err(PyFeagiError::from)?;

        self.inner.sensor_write_segmented_vision_absolute(cortical_group_index, cortical_channel_index, &wrapped_io_data)
            .map_err(PyFeagiError::from)?;
        Ok(())
    }

    pub fn sensor_update_stage_segmented_vision_absolute(&mut self, py: Python<'_>, group: PyObject, channel: PyObject,
                                                         pipeline_stage_property_index: PyObject, stage: PyObject) -> PyResult<()> {
        let cortical_group_index: CorticalGroupIndex = PyCorticalGroupIndex::try_get_from_py_object(py, group).map_err(PyFeagiError::from)?;
        let cortical_channel_index: CorticalChannelIndex = PyCorticalChannelIndex::try_get_from_py_object(py, channel).map_err(PyFeagiError::from)?;
        let stage_property_index: PipelineStagePropertyIndex = PyPipelineStagePropertyIndex::try_get_from_py_object(py, pipeline_stage_property_index).map_err(PyFeagiError::from)?;

        // Extract PyObject to Py<PyPipelineStageProperties>
        let stage_py: Py<PyPipelineStageProperties> = stage.extract(py)?;
        let pipeline_stage_properties = extract_pipeline_stage_properties_from_py(py, stage_py).map_err(PyFeagiError::from)?;

        self.inner.sensor_update_stage_segmented_vision_absolute(cortical_group_index, cortical_channel_index,
                                                                 stage_property_index, pipeline_stage_properties)
            .map_err(PyFeagiError::from)?;
        Ok(())
    }

    //endregion


    //endregion


    //region Motors

    pub fn encode_data_from_bytes_to_cache(&mut self, py: Python<'_>) -> PyResult<()> {
        self.inner.motor_update_data_from_bytes().map_err(|err| PyFeagiError::from(err))?;
        Ok(())
    }

    pub fn motor_get_byte_container(&mut self, py: Python<'_>) -> PyResult<PyFeagiByteContainer> {
        let byte_container = self.inner.motor_copy_feagi_byte_container();
        Ok(byte_container.into())
    }

    pub fn motor_set_byte_container(&mut self, py: Python<'_>, feagi_byte_container: PyFeagiByteContainer) -> PyResult<()> {
        self.inner.motor_replace_feagi_byte_container(feagi_byte_container.into());
        Ok(())
    }

    //endregion


    //region Reflexes (premade callbacks)

    pub fn reflex_absolute_gaze_to_absolute_segmented_vision(&mut self, py: Python<'_>, gaze_group: PyObject, gaze_channel: PyObject, segmentation_group: PyObject, segmentation_channel: PyObject) -> PyResult<()> {

        let gaze_group: CorticalGroupIndex = PyCorticalGroupIndex::try_get_from_py_object(py, gaze_group).map_err(PyFeagiError::from)?;
        let gaze_channel: CorticalChannelIndex = PyCorticalChannelIndex::try_get_from_py_object(py, gaze_channel).map_err(PyFeagiError::from)?;

        let segmentation_group: CorticalGroupIndex = PyCorticalGroupIndex::try_get_from_py_object(py, segmentation_group).map_err(PyFeagiError::from)?;
        let segmentation_channel: CorticalChannelIndex = PyCorticalChannelIndex::try_get_from_py_object(py, segmentation_channel).map_err(PyFeagiError::from)?;

        self.inner.reflex_absolute_gaze_to_absolute_segmented_vision(gaze_group, gaze_channel, segmentation_group, segmentation_channel).map_err(PyFeagiError::from)?;

        Ok(())
    }

    //endregion
}
